services:
  app:
    container_name: cessecrets-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - ./var/backend/messages:/project/messages
