name: CI

on:
  pull_request:
    branches: [master]
    paths:
      - "backend/**"
      - ".github/workflows/ci.yaml"
  workflow_call:

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - run: cp .env.template .env
      - run: uv sync

      - name: Ruff
        run: uv run ruff check src

      - name: Mypy
        run: uv run mypy src
